### ISSUE TITLE
Exercício 2 - Resposta - Tarefas Técnicas

### ISSUE THREAD

**Issue by MuriloSanches00** [MuriloSanches00/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-3#11]
> Analisar o trajeto a ser percorrido;
> Identificar possíveis obstáculos e peculiaridades do trajeto;
> Selecionar um robô que atenda as especificidades do trajeto a ser percorrido;
> Montar o robô;
> Adicionar um código ao robô;
> Testar o robô em uma pista de testes;
> Identificar, desenvolver e aplicar possíveis melhorias no robô;
> Testar o robô no trajeto real;
> Fazer correções e melhorias no robô e no código (caso seja necessário).

**Comment by HamiltonFilho** [comment]
Esta é uma mensagem para confirmar que este exercício foi considerado ENTREGUE COM SUCESSO pelo grupo, e isto irá refletir de forma positiva na nota A2 de todos os membros desta equipe
