### ISSUE TITLE
História 1 - Controlar robô.

### ISSUE THREAD

**Issue by MuriloSanches00** [MuriloSanches00/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-3#6]
Como controlador do robô, para passar instruções de posicionamento à maquina, gostaria de uma forma para auxiliar o processo.

**Comment by HamiltonFilho** [comment]
A história acima está quase correta!

O trecho "utilizarei de um aplicativo de celular" está explicando COMO o problema será resolvido, e isto deve ser omitido da história. A razão é que pessoas de negócios geralmente não tem experiência técnica para definir soluções, e não deveriam direcionar como especialistas trabalham

História 1 - Como gestor de recursos humanos, gostaria de uma funcionalidade para administrar o horário de entrada dos meus funcionários

**Comment by HamiltonFilho** [comment]
Esta é uma mensagem para confirmar que este exercício foi considerado ENTREGUE COM SUCESSO pelo grupo, e isto irá refletir de forma positiva na nota A2 de todos os membros desta equipe
